### ISSUE TITLE
개발 환경 설정

### ISSUE THREAD

**Issue by jintaeyeong** [jintaeyeong/Project#11]
Flutter + Spring Boot(kotlin) + MySql 기술 스택으로 결정

자바 21 버전 설치

Flutter는 이미 안드로이드 스튜디오를 설치하여 환경 설정 완료 되어있으며,
Spring Boot와 MySql에 대한 기능과 프로그램은 설치필요함

**Comment by jintaeyeong** [comment]
Spring Boot에 대한 간단한 이론, 지식 공부 후 환경 설정 

## Spring Boot 환경 설정 

1. JDK 설치
[jdk 설치 url](https://adoptopenjdk.net/)
OpenJDK21U-jdk_x64_windows_hotspot_21.0.4_7
![image](https://github.com/user-attachments/assets/6d8a4394-44c3-4cf2-8a56-b0faa5ae9f7a)


2. IDE 설치 
IntelliJ IDEA , Community 버전 설치
[IntelliJ url](https://www.jetbrains.com/idea/download/?section=windows)

**Comment by jintaeyeong** [comment]
IntelliJ Ultimate 버전을 설치하여 community 버전으로 다시 설치 
[Community 다운로드 URL ](https://www.jetbrains.com/ko-kr/idea/download/other.html)

**Comment by jintaeyeong** [comment]
# Spring Boot Initalizr 프로젝트 생성 
[spring boot 프로젝트 생성 참고 url](https://jincchan.tistory.com/m/48)

spring initializer은 스프링 부트 세팅을 간편하게 만들어준다..

1. https://start.spring.io/ 설정
![image](https://github.com/user-attachments/assets/9b204cc4-a574-41d2-9526-e3cf74aab955)

2. zip 파일 다운로드 후 압축 해제 
3. 인텔리제이 ide로 폴더 실행

4. SDK 설정이 안되어있어서 Kotlin SDK로 설정

![image](https://github.com/user-attachments/assets/8c097116-675c-4952-ad9b-fd55329dc5a1)

5. 서버 실행
![image](https://github.com/user-attachments/assets/76d9d6df-0af4-4681-8e48-39d168e9d705)

**Comment by jintaeyeong** [comment]
# MySQL 설치

![image](https://github.com/user-attachments/assets/4973580c-1197-4ea0-902e-2c134ad78d76)

mysql 버전 8.0.34로 설치

![image](https://github.com/user-attachments/assets/4ea23384-6c83-4c49-8c05-751391b25fe9)

**Comment by jintaeyeong** [comment]
[참고 사이트](https://blog.naver.com/cjs0308cjs/223369860906)

포트 3306 기본으로 설정
![image](https://github.com/user-attachments/assets/88920b65-1924-4260-9ad5-d90d1a8f1021)

![image](https://github.com/user-attachments/assets/54afc7f4-de99-46a7-9d38-828b33e89cad)
MySQL root 계정 비밀번호 설정

![image](https://github.com/user-attachments/assets/8512fbaf-63c2-472f-a2f2-2033cbf636ad)
모든 권한 위임

![image](https://github.com/user-attachments/assets/2bf6d7c1-08d2-4c5b-9892-58acbc8e7a2d)
비밀번호 입력하여 서버 연결 확인

![image](https://github.com/user-attachments/assets/0cb53100-a02a-4cb9-999b-1e8fe81d94b8)
설치 완료

**Comment by jisu-virnect** [comment]
👍
