### ISSUE TITLE
유스케이스 그리기

### ISSUE THREAD

**Issue by jintaeyeong** [jintaeyeong/Project#4]
피그마로 유스케이스 그리는 중...

**Comment by jintaeyeong** [comment]
Draw.io로 작업 중

**Comment by jintaeyeong** [comment]
1차 유스케이스 작성.. 
Actor 하나에 모든 기능을 작성하지 않고 기능을 기준으로 그렸습니다. 

https://drive.google.com/file/d/1eLfb5Y8Zh8hMKQmgPh7fLvUjw3Npva9D/view?usp=sharing

**Comment by jintaeyeong** [comment]
유스케이스 작성하면서 참고한 사이트 
https://velog.io/@kansun12/SW%EC%9D%B4%EB%A1%A0-%EC%9C%A0%EC%8A%A4%EC%BC%80%EC%9D%B4%EC%8A%A4
https://googry.tistory.com/2

**Comment by jongfeel** [comment]
추가로 draw.io도 이미지가 아니라 공유 기능이 있을 겁니다.

그리고 아래와 같은 오픈 소스를 이용하면 미리 보기도 가능할 것 같네요.

https://github.com/jgraph/drawio-github?tab=readme-ov-file
